# from .modeling_baseline_new import ElectraForMolweni_adjacent as ElectraBaseline
from .modeling_baseline_new import ElectraForMolweni as ElectraBaseline
from .modeling_baseline_new import BertForMolweni as BertBaseline
from .modeling_baseline_new import RobertaForMolweni as RobertaBaseline